"""Initial consolidated migration

Revision ID: 312dbc1dc93d
Revises: 
Create Date: 2025-06-23 15:52:35.415855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312dbc1dc93d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    # Вставка начальных данных в таблицу roles
    op.execute("INSERT INTO roles (title) VALUES ('USER'), ('ADMIN')")

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('paternal_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('ban_date', sa.DateTime(), nullable=True),
    sa.Column('role_title', sa.String(length=50), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_token', sa.Text(), nullable=True),
    sa.Column('confirmation_token_created_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_token_created_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_title'], ['roles.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_email'), 'refresh_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_email'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Удаление начальных данных из таблицы roles
    op.execute("DELETE FROM roles WHERE title IN ('USER', 'ADMIN')")
    op.drop_table('roles')
    # ### end Alembic commands ###
